---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age166sf7zvhctxarkvh9e4z2xc978cy9s8xz5yel7j6tpvppn56d3mslstnnk"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age166sf7zvhctxarkvh9e4z2xc978cy9s8xz5yel7j6tpvppn56d3mslstnnk"
