---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2023.10.7
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:16
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: authentik-secret
    podAnnotations:
      secret.reloader.stakater.com/reload: authentik-secret
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hosts:
        - host: &host authentik.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: *host
    envFrom:
      - secretRef:
          name: authentik-secret
    postgresql:
      enabled: false
    redis:
      enabled: false
    geoip:
      enabled: false
    prometheus:
      rules:
        create: true
      serviceMonitor:
        create: true
    authentik:
      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
      redis:
        host: "authentik-redis.security.svc.cluster.local"
        password: ""
