---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      defaultFsType: ext4
      reclaimPolicy: Delete
    defaultSettings:
      backupstorePollInterval: 300
      defaultDataPath: /mnt/usb
      backupTarget: s3://longhorn@weur/
      backupTargetCredentialSecret: longhorn-backup-secret
      # backupTarget: nfs://${NAS_ADDR}:/mnt/external/longhorn-backups
      defaultDataLocality: best-effort
      defaultReplicaCount: 3
      defaultLonghornStaticStorageClass: longhorn
      createDefaultDiskLabeledNodes: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      storageMinimalAvailablePercentage: 10
      StorageOverProvisioningPercentage: 120
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: "cow"
          hajimari.io/appName: "Longhorn"
          hajimari.io/targetBlank: "true"
          hajimari.io/info: "Storage"
        hosts:
          - host: &host "{{ .Release.Name }}-external.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    metrics:
      serviceMonitor:
        enabled: true
