---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      defaultFsType: ext4
      reclaimPolicy: Delete
    defaultSettings:
      backupstorePollInterval: 300
      defaultDataPath: /mnt/usb
      backupTarget: s3://longhorn@weur/
      backupTargetCredentialSecret: longhorn-backup-secret
      # backupTarget: nfs://${NAS_ADDR}:/mnt/external/longhorn-backups
      defaultDataLocality: best-effort
      defaultReplicaCount: 3
      defaultLonghornStaticStorageClass: longhorn
      createDefaultDiskLabeledNodes: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      storageMinimalAvailablePercentage: 10
      StorageOverProvisioningPercentage: 120
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        nginx.ingress.kubernetes.io/auth-url: |-
          https://authentik-server.security.svc.cluster.local/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-signin: |-
          https://authentik.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: |-
          Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Host $http_host;
      host: longhorn.${SECRET_DOMAIN}
      tls: true
      tlsSecret: longhorn-tls
    metrics:
      serviceMonitor:
        enabled: true
