---
<<<<<<< HEAD
# yaml-language-server: $schema=https://raw.githubusercontent.com/axeII/crds/main/helmrelease_v2beta1.json
=======
# yaml-language-server: $schema=https://kubernetes-schemas.kashall.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
>>>>>>> 4fbd0f4046c06f881dfd6ba7a3900460bfc08ddd
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: external-secrets
      version: 0.9.12
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    replicaCount: 1
    leaderElect: true
    serviceMonitor:
      enabled: true
      interval: 1m
    webhook:
      serviceMonitor:
        enabled: true
        interval: 1m
    certController:
      serviceMonitor:
        enabled: true
        interval: 1m
