apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:LKzPzvS4/5JLROfPWMqLftTO3Espmk+O7wRZgC5fNDA=,iv:NzkGID9gv7WFiw8TyooYDWpJiTa8ru4O5C3vlbmndgg=,tag:ywlGF28q1jKUOemunfwBaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166sf7zvhctxarkvh9e4z2xc978cy9s8xz5yel7j6tpvppn56d3mslstnnk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Q3E3R0VlQUNzUzdGcEUy
            T3cwd0EzYzVkbmhsVkJMRmM2ajR3bmVPa2tnCmswUzdvS3ZhZFFrbzROUzJUMVlH
            YTZ6amtjYzhMbzFBOXRGYXphSlhGOU0KLS0tIE9MMTE2cFN4aFcyLzBoSlJPVk0w
            WENYdjFJeTBCK3BaaFRraWRVVWNFeFkKNGp/oFSmSUipvbmy3vf2Kuz2WN1AK8O6
            W4qO5qTTGoG9ZvedqcqCKH1/V5D7SHOJbtmEVm5+19hv+FEud6bxkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-17T10:18:13Z"
    mac: ENC[AES256_GCM,data:xuUpig2DabUL5+nK/0yWmdcN7weExVSV0EG4BWgWXaYUQKRCLLhuIBYi5zAlXlw6YPPQpKaSRrVdo99slk2y1ZNEqIYXRQYSTljbqF9RhHUosD9UpRgfbGTwig8mBAFdbPezMsQnI5pSDXIYFIcpi6t+cPg5RFbbKfEhqj3Kg9o=,iv:6Zh0M34U7aKc5WRDM6Odx3gX/+EPyv31Cs1fQ2ZYAHo=,tag:3h4CEE7/jeXCyf3f8gc03w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
