apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:pvt7jEYKMc+d3fRMq5OEBZrFVMf//1PE+j6py5cYq1c=,iv:H3snUjVuVVBEXOXogwMZI+AUEIcmJn0drtcfQsZ5sB4=,tag:r7EJCGlla/mlp1g3iUXn2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166sf7zvhctxarkvh9e4z2xc978cy9s8xz5yel7j6tpvppn56d3mslstnnk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYVlRa2RwcmdtWndkc01s
            OERVY01Pdk1MWHprOWZXRTk4N1RGQVF0U2xBCnBiWHhqM01aSlZ4TEw1SSsyNUZs
            Rm84WEJYNmJWUXZzNjM3citxTjlzMDAKLS0tIGdnTnVCQ3VsdFYxZjVtWGVlN2Z1
            akdxWVREMEJRU2Y1RHhTaFFFZXVFcXcKjP7mgjm9tiTodfCt2H2GyIgKGYbZOqVK
            eMrfVBRVrq9kWaBP+N0JJ+vL1mTr1RiSngKjLkH8iBuz52Gvcf8Xjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T20:27:05Z"
    mac: ENC[AES256_GCM,data:7Y0CEc/mr94j1550NxtOq7iIGEZ/1yZshHn0z+cNfpY+G55M8315wl2trykNgXRcaM/CenkQVh6ZvK0Cl23r5yjdVXH4Paq1PjxrX2it2rCZ6oCEJJ28SnD0QqsvcpKn3Slo1QeMg/A0wDAXEJBLAEB+3+o09KQLZqhwJLLM7Wg=,iv:kQ7S/xrzCwVOqIsxOVVQuSLXwG51HAJAASEJOT0F5nI=,tag:h5Qx39uYvkgJ498C1BQmgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
